%% ============================================================
% PSD visualization of SEEG recordings
%
% Description:
%   Plot subject-level PSD curves with 95% confidence intervals
%   across different experimental states.
%
% MATLAB version:
%   R2020b
%
% Input:
%   PSD_*.mat generated by PSD analysis pipeline
%
% Output:
%   PSD figures for each ROI
%
% ============================================================


clear;
clc;
close all;



%% ===== 字体设置 =====

set(0, 'DefaultAxesFontName', 'Times New Roman');

set(0, 'DefaultTextFontName', 'Times New Roman');

set(0, 'DefaultLegendFontName', 'Times New Roman');


set(0, 'DefaultAxesFontSize', 12);

set(0, 'DefaultTextFontSize', 12);



%% ======================== 数据路径 ========================

% User-defined folder containing PSD mat files

data_dir = 'YOUR_PSD_RESULT_FOLDER';



ROI_list = {'PFC','HPC'};


ROI_labels.PFC = 'Frontal cortex PSD';

ROI_labels.HPC = 'Hippocampus PSD';



states = {'MAIN','ANE','ETT','AWA','WARD'};

stateLabels = {'ANE','R-5','R+5','R+25','WARD'};



%% ======================== 颜色 ========================

color.MAIN = [0.85 0.33 0.10];

color.ANE  = [0.93 0.69 0.13];

color.ETT  = [0.00 0.45 0.74];

color.AWA  = [0.47 0.67 0.19];

color.WARD = [0 0 0];



%% ======================== 主循环（ROI）========================

for r = 1:length(ROI_list)


    roi_name = ROI_list{r};



    %% ===== 加载数据 =====

    file = fullfile(data_dir,...
        ['PSD_' roi_name '.mat']);


    load(file);



    figure('Position',[100 100 900 600]);

    hold on;



    plotHandle = gobjects(length(states),1);



    %% ======================== 状态循环 ========================

    for s = 1:length(states)


        state = states{s};



        if ~isfield(PSD,state)

            warning('%s 缺失',state);

            continue;

        end



        data = PSD.(state);



        if isempty(data)

            warning('%s 无数据',state);

            continue;

        end



        %% ===== 均值 + CI =====

        meanPSD = mean(data,1);


        stdPSD = std(data,0,1);


        nSub = size(data,1);



        ci95 = 1.96 * stdPSD ./ sqrt(nSub);



        upper = meanPSD + ci95;


        lower = meanPSD - ci95;



        x = freq;



        %% ===== CI ribbon =====

        patch([x fliplr(x)],...

              [upper fliplr(lower)],...

              color.(state),...

              'FaceAlpha',0.2,...

              'EdgeColor','none',...

              'HandleVisibility','off');



        %% ===== 均值曲线 =====

        plotHandle(s) = plot(x,meanPSD,...

            'Color',color.(state),...

            'LineWidth',2,...

            'DisplayName',stateLabels{s});



    end



    %% ======================== 图形设置 ========================


    xlabel('Frequency (Hz)');


    ylabel('Power Spectral Density (dB)');



    title(ROI_labels.(roi_name),...

        'FontWeight','bold');



    xlim([0.5 100]);


    ylim([-20 40]);



    %% ===== 对数坐标 =====

    set(gca,'XScale','log');



    %% ===== 关键频点 =====

    ax = gca;


    ax.XTick = [0.5 1 2 4 8 13 30 60 100];


    ax.XTickLabel = {'0.5','1','2','4','8','13','30','60','100'};



    %% ===== 网格 =====

    grid off;


    box off;


    set(gca,'LineWidth',1.5);



    %% ===== 图例 =====

    legend('show','Location','northeast');



end