%% ============================================================
% Band-specific PSD statistical comparison and visualization
%
% Description:
%   Extract band-specific PSD values from ROI-level PSD results,
%   perform paired Wilcoxon signed-rank comparisons between states,
%   apply FDR correction, and generate boxplots.
%
% MATLAB version:
%   R2020b
%
% Input:
%   PSD_*.mat generated by PSD analysis pipeline
%
% Statistical analysis:
%   - Wilcoxon signed-rank test
%   - Benjamini-Hochberg FDR correction
%
% Output:
%   TIFF figure
%
% ============================================================


clear;
clc;
close all;



%% ================= 可控参数（只改这里） =================

ROI_name = 'PFC';          % 'PFC' or 'HPC'

band     = [13 30];        % frequency band



%% ================= 全局字体 =================

set(0,'DefaultAxesFontName','Times New Roman');

set(0,'DefaultTextFontName','Times New Roman');

set(0,'DefaultLegendFontName','Times New Roman');



%% ================= 路径 =================

% Folder containing PSD_*.mat files

PSD_result_dir = 'YOUR_PSD_RESULT_FOLDER';


data_file = fullfile(PSD_result_dir,...
                     ['PSD_' ROI_name '.mat']);


load(data_file);



%% ================= 颜色 =================

color.MAIN = [0.85 0.33 0.10];

color.ANE  = [0.93 0.69 0.13];

color.ETT  = [0.00 0.45 0.74];

color.AWA  = [0.47 0.67 0.19];

color.WARD = [0 0 0];


color_map = [ ...
    color.MAIN;
    color.ANE;
    color.ETT;
    color.AWA;
    color.WARD];



%% ================= 频段提取 =================

idx = freq >= band(1) & freq <= band(2);


MAIN = mean(PSD.MAIN(:,idx),2);

ANE  = mean(PSD.ANE(:,idx),2);

ETT  = mean(PSD.ETT(:,idx),2);

AWA  = mean(PSD.AWA(:,idx),2);

WARD = mean(PSD.WARD(:,idx),2);


data_all = {MAIN, ANE, ETT, AWA, WARD};



%% ================= 补 NaN =================

maxN = max(cellfun(@length,data_all));

data_mat = nan(maxN,5);


for i = 1:5

    data_mat(1:length(data_all{i}),i) = data_all{i};

end



%% ================= 画图 =================

figure('Color','w');

hold on;


boxplot(data_mat,...
    'Labels',state_labels,...
    'Symbol','k.');



%% ===== 上色 =====

boxes = findobj(gca,'Tag','Box');


for i = 1:length(boxes)

    patch(get(boxes(i),'XData'),...
          get(boxes(i),'YData'),...
          color_map(end-i+1,:),...
          'FaceAlpha',0.5);

end



ylabel('PSD (dB)');



%% ===== ROI名称映射 =====

if strcmpi(ROI_name,'PFC')

    roi_label = 'Frontal cortex';

elseif strcmpi(ROI_name,'HPC')

    roi_label = 'Hippocampus';

else

    roi_label = ROI_name;

end



title(sprintf('%s (%.1f–%.1f Hz)',...
    roi_label,...
    band(1),...
    band(2)));



set(gca,...
    'FontSize',12,...
    'LineWidth',1.2);



%% =====================================================
%% ================= 两两比较 ===========================
%% =====================================================


nStates = 5;

nComp = nchoosek(nStates,2);


p_vals = zeros(nComp,1);

pairs = zeros(nComp,2);



c = 0;


for i = 1:nStates-1

    for j = i+1:nStates


        c = c + 1;


        x = data_mat(:,i);

        y = data_mat(:,j);


        valid = ~isnan(x) & ~isnan(y);


        x = x(valid);

        y = y(valid);



        if length(x)<3

            p_vals(c)=NaN;

        else

            p_vals(c)=signrank(x,y);

        end


        pairs(c,:)=[i j];


    end

end



%% ===== FDR correction =====

p_fdr = mafdr(p_vals,'BHFDR',true);



%% =====================================================
%% ===== 显著性标注 ====================================
%% =====================================================


ymax = max(data_mat(:));

ymin = min(data_mat(:));

yrange = ymax-ymin;


h_gap = 0.05*yrange;

h_line = 0.35*h_gap;


y = ymax+h_gap;


y_top = ymax;



for i = 1:nComp


    if isnan(p_fdr(i)) || p_fdr(i)>=0.05

        continue;

    end



    x1 = pairs(i,1);

    x2 = pairs(i,2);



    if p_fdr(i)<0.001

        sig='***';

    elseif p_fdr(i)<0.01

        sig='**';

    else

        sig='*';

    end



    plot([x1 x1],...
         [y y+h_line],...
         'k',...
         'LineWidth',1.2);


    plot([x2 x2],...
         [y y+h_line],...
         'k',...
         'LineWidth',1.2);


    plot([x1 x2],...
         [y+h_line y+h_line],...
         'k',...
         'LineWidth',1.2);



    y_star = y+1.5*h_gap;


    text(mean([x1 x2]),...
         y_star,...
         sig,...
         'HorizontalAlignment','center',...
         'FontSize',12,...
         'FontWeight','bold');



    y_top=max(y_top,y_star);


    y=y+2*h_gap;


end



%% ===== 精准ylim =====

margin=0.8*h_gap;

ylim([ymin y_top+margin]);



%% ===== 外观 =====

grid off;

box off;



%% ================= 保存 TIFF =================


save_name = sprintf('%s_%d-%dHz.tiff',...
    ROI_name,...
    band(1),...
    band(2));


save_full = fullfile(PSD_result_dir,save_name);



set(gcf,'PaperPositionMode','auto');


print(gcf,...
      save_full,...
      '-dtiff',...
      '-r300');



fprintf('TIFF saved -> %s\n',save_full);


disp('===== REUSABLE FIGURE DONE =====')